- name: MySQL | package requirements
  apt: name={{ item }} state=present update_cache=yes
  with_items:
  - mysql-server-5.5
  - mysql-client-5.5

- name: MySQL | Ensure MySQL is running
  service:
    name: mysql
    state: started

- name: MySQL | Set the root password.
  mysql_user:
    user: root
    host: "{{item}}"
    password: "{{ mysql_root_password }}"
  with_items:
   - "{{ansible_hostname}}"
   - 127.0.0.1
   - ::1
   - localhost
  when: ansible_hostname != 'localhost'

- name: MySQL | Configure MySql for easy access as root user
  template:
    src: root_my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: MySQL | Remove the MySQL test database
  mysql_db:
    name: test
    state: absent

- name: add mysql user
  mysql_user: name={{ ideato_mysql_user }}
              host={{ item }}
              password={{ ideato_mysql_password }} priv=*.*:ALL,GRANT
              login_user=root
              login_password={{ ideato_mysql_password }}
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: create mysql databases
  mysql_db: name={{ item }}
            state=present
  with_items:
    - "{{ ideato_mysql_db }}"



